install.packages("ggplot2")
install.packages("tidyverse")
house_data <- read.csv("C:\\Users\\prane\\OneDrive\\Desktop\\house-prices.csv")
library(ggplot2)
library(tidyverse)
str(house_data)
house_numeric <- house_data[, c("Price", "SqFt", "Bedrooms", "Bathrooms", "Offers")]
house_numeric <- na.omit(house_numeric)
scaled_data <- scale(house_numeric)
pca_result <- prcomp(scaled_data, center = TRUE, scale. = TRUE)
summary(pca_result)
plot(pca_result, type = "l", main = "Scree Plot - PCA on House Data")
biplot(pca_result, main = "PCA Biplot")
